#ifndef UMDH_DATAMODEL_SERIALIZER_GLOBAL
#define UMDH_DATAMODEL_SERIALIZER_GLOBAL

#if defined(UMDH_DATAMODEL_SERIALIZER_LIBRARY)
#  define UMDH_DATAMODEL_SERIALIZER_EXPORT __declspec(dllexport)
#else
#  define UMDH_DATAMODEL_SERIALIZER_EXPORT __declspec(dllimport)
#endif

#endif // UMDH_DATAMODEL_GLOBAL
